### ISSUE TITLE
Bug with directory separators on Linux

### ISSUE THREAD

**Issue by JaschaKauth** [anantshri/svn-extractor#10]
In Line 85/86 you wrote:
```python
if not folder.endswith('\\'):
     folder = folder  + "\\"
```

On Linux Systems it creates the right directory, but the files are in the wrong directory are named "dirname\filename".

I have solved it for Linux only by replace the '\\' with '/' both times

```python
if not folder.endswith('/'):
      folder = folder  + "/"
```

**Comment by anantshri** [comment]
I have made some changes in code and i have also added some other exception handling checks. Hopefully that should solve this problem.

os.path.sep would be the right thing to use in this case and that's what i have added.
