### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by cclements** [anantshri/svn-extractor#13]
When trying to run this on a site with /.svn/ available with:

python svn_extractor.py --url "https://<redacted>/.svn"

I get the error message:

File "svn_extractor.py", line 27
    print urli + old_line
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by anantshri** [comment]
Ah this is python3 if i am not wrong. try running with python2 this should get it going.

**Comment by cclements** [comment]
Yep, that took care of it.  Thanks!
